[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--pspec --cov-report term-missing --cov=requester --doctest-modules"

[tool.mypy]
strict = true
warn_return_any = true

[tool.isort]
profile = "black"
